// automatically generated by the FlatBuffers compiler, do not modify

namespace feather.fbs
{
    using FlatBuffers;

    struct DateMetadata : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DateMetadata GetRootAsDateMetadata(ByteBuffer _bb) { return GetRootAsDateMetadata(_bb, new DateMetadata()); }
  public static DateMetadata GetRootAsDateMetadata(ByteBuffer _bb, DateMetadata obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DateMetadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartDateMetadata(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<DateMetadata> EndDateMetadata(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DateMetadata>(o);
  }
};


}
