// automatically generated by the FlatBuffers compiler, do not modify

namespace feather.fbs
{

    enum TypeMetadata : byte
{
 NONE = 0,
 CategoryMetadata = 1,
 TimestampMetadata = 2,
 DateMetadata = 3,
 TimeMetadata = 4,
};


}
